server:
  servlet:
    context-path:
  port: 7070

service:
  registry:
    expose-host: 127.0.0.1
    expose-port: ${server.port}
    consul-host: 127.0.0.1
    consul-port: 8500

spring:
  application:
    name: gateway-server
    group: com.poly.iu.mg
  profiles:
    active: dev
  redis:
    enabled: true
    type: 1
    host: localhost
    port: 6379
    password:
    timeout: 10000
    database: 8
    ttl: 60
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 2
        max-wait: 3000
      shutdown-timeout: 10000
      command-timeout: 60000
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-interval: 5s
        service-name: ${spring.application.name}
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}/info
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 86400
      routes:
        - id: 用户服务
          uri: lb://user-server
          predicates:
            - Path=/user-server/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                # 每秒可以请求的次数
                redis-rate-limiter.burstCapacity: 2
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback
        - id: 订单服务
          uri: lb://order-server
          predicates:
            - Path=/order-server/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@apiKeyResolver}"
                redis-rate-limiter.replenishRate: 2
                redis-rate-limiter.burstCapacity: 2
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback

ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

alibaba:
  acm:
    group: ${group:DEFAULT_GROUP}
    endpoint: ${endpoint:acm.aliyun.com}
    fileExtension: ${fileExtension:yaml}
    namespace: ${namespace:52e0a4cb-7dc1-4346-bb1d-abd3eb4afdd0}
    ramRoleName: ${ramRoleName:KubernetesWorkerRole-68f28ddc-6c89-41b4-9cef-5346700fa861}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always
info: {status: ok}

jwt:
  signing:
    key: cf7031334895495582bf05fa6d2f57e1

open:
  path:
    global: /*/v2/api-docs;/*/info;/*/open/**