server:
  servlet:
    context-path:
  port: 8004

service:
  registry:
    expose-host: 127.0.0.1
    expose-port: ${server.port}
    consul-host: 127.0.0.1
    consul-port: 8500

spring:
  application:
    name: gateway-server
    group: com.poly.iu.mg
  profiles:
    active: dev
  redis:
    enabled: true
    type: 1
    host: localhost
    port: 6379
    password:
    timeout: 10000
    database: 1
    ttl: 60
    lettuce:
      pool:
        max-active: 500
        max-idle: 10
        min-idle: 2
        max-wait: 3000
      shutdown-timeout: 10000
      command-timeout: 60000
  cloud:
    consul:
      host: ${service.registry.consul-host}
      port: ${service.registry.consul-port}
      discovery:
        health-check-interval: 5s
        service-name: ${spring.application.name}
        health-check-url: http://${service.registry.expose-host}:${service.registry.expose-port}/info
        enabled: true
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"
            maxAge: 86400

ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 30000
  ConnectTimeout: 30000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#阿里云分布式配置中心
alibaba:
  acm:
    group: ${group:DEFAULT_GROUP}
    endpoint: ${endpoint:acm.aliyun.com}
    fileExtension: ${fileExtension:yaml}
    namespace: ${namespace:xxxx}
    ramRoleName: ${ramRoleName:KubernetesWorkerRole-xxx}

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      show-details: always
info: {status: ok}

rocketmq:
  name-server: http://xxx.mq-internet-access.mq-internet.aliyuncs.com:80
  producer:
    access-key: xxx
    secret-key: zzz
    group: hhh
    sendMessageTimeout: 300000
    topic:
      log: saas-normal
    tag:
      log: message-log-dev

# 单点登录
custom:
  sso:
    jwtSigningKey: xzxzxz

global:
  open:
    paths: /*/info;/*/v2/api-docs;/*/open/api/**
